server:
  port: 8082

spring:
  application:
    name: matching-engine-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
        acks: "1"
        linger.ms: 2
        batch.size: 16384
    consumer:
      group-id: matching-engine
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.oms.common.dto"
        max.poll.records: 500
        fetch.min.bytes: 1
        fetch.max.wait.ms: 100

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.oms: INFO
